language: objective-c
osx_image: xcode11
script:
- xcrun xcodebuild -project Attabench.xcodeproj -scheme Attabench
- swift build
- (cd ExampleBenchmarks/SampleBenchmark.attabench && swift build)
- (cd ExampleBenchmarks/OptimizingCollections.attabench && swift build)
